/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasBesar.pbo.kelompok1.betuahApps.view.user;

/**
 *
 * @author Salsabila
 */
public class ProfileView extends javax.swing.JPanel {

    /**
     * Creates new form ProfileView
     */
    public ProfileView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelProfile = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelFoto = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelInputNama = new javax.swing.JLabel();
        jLabelInputUsername = new javax.swing.JLabel();
        jLabelInputEmail = new javax.swing.JLabel();
        jButtonEditProfile = new rojerusan.RSMaterialButtonRectangle();

        setPreferredSize(new java.awt.Dimension(1820, 1050));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelProfile.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelProfile.setForeground(new java.awt.Color(112, 74, 0));
        jLabelProfile.setText("PROFILE");

        jPanel2.setPreferredSize(new java.awt.Dimension(1298, 564));

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasBesar/pbo/kelompok1/betuahApps/view/user/profile3.png"))); // NOI18N
        jLabelFoto.setPreferredSize(new java.awt.Dimension(567, 512));

        jLabelNama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNama.setText("Nama:");

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUsername.setText("Username:");

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelEmail.setText("Email:");

        jLabelInputNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInputNama.setText("Ratuayu Nurfajar");

        jLabelInputUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInputUsername.setText("Ratuayu");

        jLabelInputEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInputEmail.setText("ratu@gmail.com");

        jButtonEditProfile.setBackground(new java.awt.Color(209, 184, 161));
        jButtonEditProfile.setForeground(new java.awt.Color(112, 74, 0));
        jButtonEditProfile.setText("Edit Profile");
        jButtonEditProfile.setPreferredSize(new java.awt.Dimension(228, 61));
        jButtonEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNama)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelInputNama)
                    .addComponent(jLabelInputUsername)
                    .addComponent(jLabelInputEmail)
                    .addComponent(jButtonEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInputNama)
                        .addGap(57, 57, 57)
                        .addComponent(jLabelUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInputUsername)
                        .addGap(60, 60, 60)
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInputEmail)
                        .addGap(42, 42, 42)
                        .addComponent(jButtonEditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabelProfile)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelProfile)
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle jButtonEditProfile;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelInputEmail;
    private javax.swing.JLabel jLabelInputNama;
    private javax.swing.JLabel jLabelInputUsername;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelProfile;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
