/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.betuahapps.view;

import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import main.java.com.betuahapps.Koneksi;
import main.java.com.betuahapps.controller.SignInController;

/**
 *
 * @author Ocean
 */
public class SignInView extends javax.swing.JFrame {
    Koneksi koneksi;
    SignInController signincontrol;

    /**
     * Creates new form SignInView
     */
    public SignInView() {
        initComponents();
        koneksi = new Koneksi();
        signincontrol = new SignInController();
        
        jLabelEmailUsernameValid.setVisible(false);
        jLabelPasswordValid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        labelDescLogin = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelEmailUsername = new javax.swing.JLabel();
        jTextFieldEmailUsername = new javax.swing.JTextField();
        jLabelEmailUsernameValid = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelPasswordValid = new javax.swing.JLabel();
        jCheckBoxRememberMe = new javax.swing.JCheckBox();
        labelForgotPassword = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        labelDontHaveAccount = new javax.swing.JLabel();
        labelRegisterNow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(202, 174, 171));
        sidePanel.setPreferredSize(new java.awt.Dimension(650, 1080));

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        mainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightPanel.setPreferredSize(new java.awt.Dimension(1270, 1080));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setPreferredSize(new java.awt.Dimension(560, 700));

        labelDescLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDescLogin.setText("Welcome to Warmindo Betuah");

        labelLogin.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        labelLogin.setText("LOG IN TO YOUR ACCOUNT");

        labelEmailUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelEmailUsername.setText("Email atau Username :");

        jTextFieldEmailUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldEmailUsername.setText("Insert Your Email atau Username");
        jTextFieldEmailUsername.setPreferredSize(new java.awt.Dimension(482, 40));

        jLabelEmailUsernameValid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelEmailUsernameValid.setForeground(new java.awt.Color(255, 0, 0));
        jLabelEmailUsernameValid.setText("*Email atau Username tidak valid");

        labelPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPassword.setText("Password :");

        jPasswordField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField.setText("kddwoaooakod");
        jPasswordField.setPreferredSize(new java.awt.Dimension(485, 40));

        jLabelPasswordValid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelPasswordValid.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPasswordValid.setText("*Password tidak valid");

        jCheckBoxRememberMe.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxRememberMe.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxRememberMe.setText("    Remember Me");

        labelForgotPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelForgotPassword.setForeground(new java.awt.Color(202, 174, 171));
        labelForgotPassword.setText("Forgot password or username?");
        labelForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelForgotPasswordMouseClicked(evt);
            }
        });

        buttonLogin.setBackground(new java.awt.Color(202, 174, 171));
        buttonLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Login");
        buttonLogin.setPreferredSize(new java.awt.Dimension(365, 55));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        labelDontHaveAccount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDontHaveAccount.setText("You don't have an account?");

        labelRegisterNow.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelRegisterNow.setForeground(new java.awt.Color(202, 174, 171));
        labelRegisterNow.setText("Register Now");
        labelRegisterNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegisterNowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPasswordValid)
                    .addComponent(jLabelEmailUsernameValid)
                    .addComponent(labelDescLogin)
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(formPanelLayout.createSequentialGroup()
                            .addComponent(jCheckBoxRememberMe)
                            .addGap(150, 150, 150)
                            .addComponent(labelForgotPassword))
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPassword)
                            .addComponent(labelLogin)
                            .addComponent(labelEmailUsername)
                            .addComponent(jTextFieldEmailUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(formPanelLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(labelDontHaveAccount)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelRegisterNow)))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelDescLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLogin)
                .addGap(57, 57, 57)
                .addComponent(labelEmailUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEmailUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmailUsernameValid)
                .addGap(18, 18, 18)
                .addComponent(labelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPasswordValid)
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxRememberMe)
                    .addComponent(labelForgotPassword))
                .addGap(34, 34, 34)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDontHaveAccount)
                    .addComponent(labelRegisterNow))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        mainPanel.add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        getContentPane().add(mainPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getjLabelEmailUsernameValid() {
        return jLabelEmailUsernameValid;
    }

    public JLabel getjLabelPasswordValid() {
        return jLabelPasswordValid;
    }

    public JPasswordField getjPasswordField() {
        return jPasswordField;
    }

    public JTextField getjTextFieldEmailUsername() {
        return jTextFieldEmailUsername;
    }

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        signincontrol.getDatabase(this);
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void labelForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelForgotPasswordMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ForgotPasswordView().setVisible(true);
    }//GEN-LAST:event_labelForgotPasswordMouseClicked

    private void labelRegisterNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegisterNowMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new SignUpView().setVisible(true);
    }//GEN-LAST:event_labelRegisterNowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPanel formPanel;
    private javax.swing.JCheckBox jCheckBoxRememberMe;
    private javax.swing.JLabel jLabelEmailUsernameValid;
    private javax.swing.JLabel jLabelPasswordValid;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldEmailUsername;
    private javax.swing.JLabel labelDescLogin;
    private javax.swing.JLabel labelDontHaveAccount;
    private javax.swing.JLabel labelEmailUsername;
    private javax.swing.JLabel labelForgotPassword;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRegisterNow;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
